EXTRA_CLR = [
    # physics
    "why a moving car needs less force to keep going than to start",
    "what inertia is",
    "why a spinning ice skater speeds up when pulling in their arms",
    "how a microwave oven heats food",
    "why light bends when it passes from air into water",
    "what makes a gyroscope resist tipping over",
    "why a heavier flywheel is harder to spin up",
    "how noise-cancelling headphones reduce sound",
    "why a rubber band gets warm when stretched quickly",
    "what makes a tuning fork produce a single clear note",
    "why two speakers can create quiet spots in a room",
    "how a laser pointer produces a narrow beam",
    "why a plucked guitar string vibrates at a fixed pitch",
    "what causes a sonic boom",
    "why a fast-flowing river carries larger rocks",
    # chemistry
    "why cut apples turn brown",
    "what makes soap clean greasy dishes",
    "why bleach removes color from fabric",
    "how baking powder makes cakes rise",
    "why vinegar can dissolve eggshell",
    "what makes fireworks produce different colors",
    "why hydrogen peroxide foams on a wound",
    "how antacids relieve heartburn",
    "why milk turns sour over time",
    "what makes stainless steel resist rust",
    "why a candle flame needs oxygen to burn",
    "how charcoal removes odors from the air",
    "why caramel forms when sugar is heated",
    "what makes chili peppers taste hot",
    "why salt is used to preserve food",
    # biology
    "why we get goosebumps when cold",
    "how a seed knows which way to send its roots",
    "why cut flowers wilt without water",
    "how a chameleon changes color",
    "why yeast makes bread dough bubble",
    "how a spider spins its web",
    "why some animals hibernate in winter",
    "how a tadpole turns into a frog",
    "why deciduous trees lose their leaves",
    "how migrating birds find their way",
    "why a wound forms a scab",
    "how muscles get stronger with exercise",
    "why we yawn",
    "how a bird's feathers keep it warm",
    "why fish can breathe underwater",
    # human body
    "why we sneeze",
    "how the eye adjusts to dim light",
    "why our ears pop on an airplane",
    "how the stomach digests food",
    "why we shiver when cold",
    "how the brain stores memories",
    "why we feel dizzy after spinning",
    "how the body fights off a cold",
    "why we get hiccups",
    "how taste buds detect flavors",
    "why our skin wrinkles in a long bath",
    "how the kidneys filter the blood",
    "why we blink",
    "how bones heal after a fracture",
    "why we feel thirsty",
    # earth science
    "what causes a volcano to erupt",
    "how caves form underground",
    "why rivers meander across flat land",
    "how fossils form in rock",
    "why some rocks are layered",
    "how sand dunes move over time",
    "why glaciers slowly flow downhill",
    "how a geyser erupts",
    "why coastlines erode over time",
    "how soil forms from bare rock",
    "why deserts get cold at night",
    "how a delta forms at a river mouth",
    # astronomy
    "why we always see the same side of the Moon",
    "what causes a solar eclipse",
    "why comets grow tails near the Sun",
    "how a telescope gathers faint starlight",
    "why planets orbit the Sun in ellipses",
    "what makes a shooting star streak across the sky",
    "why the Sun appears to move across the sky",
    "how astronauts float inside a spacecraft",
    "why Mars looks red",
    "what causes the Northern Lights",
    # weather
    "what causes fog to form",
    "why hail forms in thunderstorms",
    "how a tornado forms",
    "why dew appears on grass in the morning",
    "what makes a hurricane spin",
    "why snowflakes have six sides",
    "how clouds form in the sky",
    "why it feels colder when the wind blows",
    "what causes lightning to strike",
    "why the air smells fresh after rain",
    # simple machines and technology
    "how a zipper holds two sides together",
    "why a screw can lift heavy loads with little effort",
    "how a bicycle's gears change pedaling effort",
    "how a wheel and axle make moving loads easier",
    "why a wedge can split a log",
    "how a touchscreen senses a finger",
    "how a microphone turns sound into a signal",
    "why a speaker cone moves to make sound",
    "how a solar panel generates electricity",
    "how a thermostat keeps a room at one temperature",
    "why an LED bulb uses less energy than a filament bulb",
    "how a key turns a lock's mechanism",
    "how a GPS device finds its location",
    "how a hard drive stores data magnetically",
    "why an inclined ramp reduces the effort to lift a load",
    # household phenomena
    "why a hot pan cools faster when you blow on it",
    "how a vacuum flask keeps drinks hot",
    "why a sponge soaks up water",
    "how a pressure cooker cooks food faster",
    "why a mirror reverses left and right",
    "how a fire extinguisher puts out flames",
    "why frost forms inside a freezer",
    "how a dimmer switch lowers a light's brightness",
    "why bubbles in soda rise to the top",
    "how a smoke detector senses smoke",
    "why a tight lid loosens when run under hot water",
    "how a wick draws fuel up a candle",
    "why double-paned windows reduce heat loss",
]
