EXTRA_CB = [
    "Governments should require large AI training datasets to be auditable by independent third parties.",
    "Companies deploying facial recognition in public spaces should obtain explicit local government approval first.",
    "AI-generated political advertising should carry a clear and prominent synthetic-content disclosure label.",
    "Algorithmic hiring tools should be tested for disparate impact before being used on real applicants.",
    "High-risk AI systems should undergo mandatory safety certification before commercial release.",
    "Social media platforms should give users a chronological feed option that is not algorithmically ranked.",
    "Children under thirteen should not be allowed to hold accounts on engagement-optimized social platforms.",
    "Critical infrastructure operators should be legally required to report major cyberattacks within seventy-two hours.",
    "Software vendors should bear some legal liability for damages caused by negligent security defects.",
    "Mobile operating systems should allow users to install applications from outside the official store.",
    "Internet service providers should disclose their actual average speeds rather than theoretical maximums.",
    "Governments should publish the source code of software used to administer public benefits.",
    "Biometric data such as fingerprints and faceprints deserves stronger legal protection than ordinary personal data.",
    "Employers should not monitor employees' personal communications on company-issued devices without disclosure.",
    "Data brokers should be required to maintain a public registry of the categories of data they sell.",
    "Individuals should have the right to obtain a copy of every inference a company has drawn about them.",
    "Genetic testing companies should need separate explicit consent before sharing data with law enforcement.",
    "Smart home devices should continue functioning locally even after the manufacturer ends cloud support.",
    "Default privacy settings on consumer products should be the most protective option available.",
    "Location data collected by apps should be deleted automatically after a short retention period by default.",
    "National grids should prioritize long-duration energy storage to manage intermittent renewable supply.",
    "Wealthy nations should fund climate adaptation infrastructure in countries most exposed to rising seas.",
    "New commercial buildings should be required to meet strict energy-efficiency standards.",
    "Subsidies for fossil fuel extraction should be phased out over the coming decade.",
    "Utilities should be allowed to charge higher rates during peak demand to encourage off-peak usage.",
    "Major corporations should disclose the full carbon footprint of their supply chains annually.",
    "Recycling programs should prioritize reducing plastic production over expanding collection capacity.",
    "Cities should expand tree canopy coverage as a primary strategy against urban heat.",
    "Airlines should be required to offer carbon-offset options that are independently verified.",
    "Agricultural water rights should be reallocated to reflect long-term scarcity rather than historical use.",
    "Central banks should treat full employment as seriously as they treat price stability.",
    "Stock buybacks should face higher taxation than dividends paid to shareholders.",
    "Antitrust enforcement should consider harm to workers, not only harm to consumers.",
    "Gig economy workers should be entitled to portable benefits funded by the platforms they serve.",
    "Companies above a certain size should disclose the ratio of executive pay to median worker pay.",
    "Noncompete agreements should be unenforceable for most low and middle-wage workers.",
    "Wealth concentrated in inherited estates should be taxed more heavily than earned income.",
    "Small businesses should receive simplified tax filing options distinct from large corporations.",
    "Workers should have the right to disconnect from work communications outside scheduled hours.",
    "Central bank digital currencies should be designed to preserve transaction privacy comparable to cash.",
    "Pharmaceutical prices should be negotiated collectively by public health systems to lower costs.",
    "Generic drug manufacturers should be supported to prevent shortages of essential medicines.",
    "Mental health care should be reimbursed by insurers at parity with physical health care.",
    "Hospitals should publish standardized, comparable prices for common procedures.",
    "Public health agencies should invest more in preventive care than in acute treatment.",
    "Medical records should follow patients seamlessly across providers without administrative friction.",
    "Antibiotic use in livestock should be restricted to protect human drug effectiveness.",
    "Clinical trial results should be publicly registered regardless of whether outcomes were favorable.",
    "Telemedicine should be permanently reimbursed at rates comparable to in-person visits.",
    "Nutrition labeling should clearly indicate added sugars separately from naturally occurring ones.",
    "Teacher salaries should be raised substantially to attract and retain qualified educators.",
    "Computer science should be a core subject in primary and secondary education.",
    "Universities should cap administrative spending growth relative to instructional spending.",
    "Vocational and apprenticeship pathways deserve funding parity with traditional college tracks.",
    "Student loan interest rates should not exceed the government's own cost of borrowing.",
    "School curricula should include practical financial literacy as a graduation requirement.",
    "Class sizes in early grades should be capped to improve learning outcomes.",
    "Public libraries should receive stable funding as essential community infrastructure.",
    "Higher education institutions should disclose graduate employment outcomes by program of study.",
    "Early childhood education should be publicly funded as a foundation for later achievement.",
    "Cities should permit denser housing construction near major transit corridors.",
    "Vacant residential properties in tight housing markets should face escalating tax penalties.",
    "Building codes should be streamlined to reduce the cost of constructing affordable housing.",
    "Pedestrians and cyclists should be prioritized over cars in dense urban cores.",
    "Intercity rail should receive sustained public investment as an alternative to short-haul flights.",
    "Zoning laws should permit small businesses to operate within residential neighborhoods.",
    "Road maintenance funding should shift from fuel taxes toward distance-based user fees.",
    "New developments should be required to include a minimum share of below-market housing units.",
    "Public spaces should be designed to be fully accessible to people with disabilities by default.",
    "Cities should convert underused parking lots into housing and green space.",
    "Basic scientific research should be funded primarily by the public rather than private interests.",
    "Research funded by taxpayers should produce data that is freely available to the public.",
    "Long-term high-risk research deserves dedicated funding insulated from short-term results pressure.",
    "Replication studies should receive funding and recognition comparable to novel findings.",
    "National research budgets should grow at least as fast as the broader economy.",
    "Scientific peer reviewers should be compensated for the time they contribute.",
    "Public funding agencies should require open sharing of research materials and methods.",
    "Early-career researchers should receive a larger share of national research grants.",
    "Space exploration should balance crewed missions with robotic science of comparable priority.",
    "Pandemic preparedness should be funded continuously rather than only during active outbreaks.",
    "Elections should be administered by nonpartisan independent bodies rather than elected officials.",
    "Voter registration should be automatic for all eligible citizens unless they opt out.",
    "Campaign finance should be subject to strict transparency requirements for all major donors.",
    "Legislative district boundaries should be drawn by independent commissions, not sitting legislators.",
    "Government meetings and records should default to public access absent a specific exemption.",
    "Lobbying contacts with public officials should be logged in a searchable public registry.",
    "Public officials should divest from assets that create conflicts with their duties.",
    "Whistleblowers who expose government wrongdoing deserve strong legal protection from retaliation.",
    "Voting should be made more convenient through expanded early and mail-in options.",
    "Regulatory agencies should be insulated from political interference in technical decisions.",
    "Trade agreements should include enforceable labor and environmental standards.",
    "Tariffs should be used sparingly and targeted rather than applied broadly across sectors.",
    "Critical supply chains should be diversified to reduce dependence on any single country.",
    "Developing economies should retain policy space to protect emerging domestic industries.",
    "Import safety inspections should be funded adequately to match growing trade volumes.",
    "Trade policy should account for the carbon emissions embedded in imported goods.",
    "Intellectual property rules in trade deals should permit affordable access to essential medicines.",
    "Cross-border data flows should be governed by mutual privacy adequacy standards.",
    "Public procurement should weigh long-term value over lowest upfront cost.",
    "Sanctions should include humanitarian exemptions to avoid harming civilian populations.",
    "Single-use plastic packaging should be phased out where reusable alternatives are practical.",
    "Manufacturers should be responsible for the end-of-life disposal of the products they sell.",
    "Protected natural areas should be expanded to safeguard biodiversity.",
    "Industrial polluters should pay for the remediation of contaminated sites.",
    "Wildlife corridors should be preserved to allow species to migrate as habitats shift.",
    "Light pollution should be limited to protect ecosystems and nocturnal wildlife.",
    "Ocean fishing quotas should be set conservatively to allow depleted stocks to recover.",
    "Public news media should be funded in a way that protects editorial independence.",
    "Newsrooms should clearly distinguish reporting from opinion content for readers.",
    "Local journalism deserves public support as a check on local government.",
    "Media organizations should disclose their ownership structure to the public.",
    "Consumers should be entitled to clear, jargon-free summaries of contract terms before signing.",
    "Subscription services should make cancellation as easy as the initial signup process.",
    "Product warranties should be honored without requiring consumers to navigate obstacles.",
    "Hidden fees should be disclosed in the advertised price rather than added at checkout.",
    "Consumers should have a guaranteed cooling-off period to cancel high-pressure purchases.",
    "Food producers should be required to disclose the country of origin of key ingredients.",
    "Companies should notify affected individuals promptly after any significant data breach.",
    "Loyalty programs should not penalize customers who decline to share additional personal data.",
    "Credit scoring models should be explainable so consumers can understand and contest their ratings.",
]
